FROM node:current-stretch

RUN dpkg --add-architecture i386
RUN apt-get update && apt-get install -y mono-complete wine wine32 build-essential --no-install-recommends

RUN npm install -g electron-builder

WORKDIR /weather-dump
ENTRYPOINT ["make", "build-gui"]
